import jsPDF from "jspdf";
import { ConsentLog } from '../../shared/schema.js';
import { format } from "date-fns";

/**
 * PDF Report Builder for INSA Compliance
 * Generates audit-ready PDF reports with watermarks, legal footers, and signature data
 */

const LEGAL_FOOTER = "Compliant with Proclamation No. 1072/2018 & No. 1205/2020 – Alga Technologies PLC © 2025";
const WATERMARK_TEXT = "INSA-READY AUDIT COPY";

interface ReportOptions {
  title: string;
  adminName: string;
  adminUserId: string;
  exportDate: Date;
}

/**
 * Add diagonal watermark to PDF page
 */
function addWatermark(doc: jsPDF): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  doc.setFontSize(60);
  doc.setTextColor(220, 220, 220); // Light gray for watermark effect
  
  // Calculate diagonal rotation
  const centerX = pageWidth / 2;
  const centerY = pageHeight / 2;
  
  doc.text(WATERMARK_TEXT, centerX, centerY, {
    angle: 45,
    align: 'center',
  });
}

/**
 * Add legal footer to PDF page
 */
function addFooter(doc: jsPDF, pageNumber: number, totalPages: number): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  
  // Legal compliance text
  doc.text(LEGAL_FOOTER, pageWidth / 2, pageHeight - 15, {
    align: 'center',
  });
  
  // Page number
  doc.text(
    `Page ${pageNumber} of ${totalPages}`,
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );
}

/**
 * Add report header
 */
function addHeader(doc: jsPDF, options: ReportOptions): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Title
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(options.title, pageWidth / 2, 20, { align: 'center' });
  
  // Export metadata
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated by: ${options.adminName} (${options.adminUserId})`, 20, 35);
  doc.text(`Export Date: ${format(options.exportDate, 'PPpp')}`, 20, 42);
  
  // Horizontal line
  doc.setLineWidth(0.5);
  doc.line(20, 48, pageWidth - 20, 48);
}

/**
 * Generate PDF report for signature consent logs
 */
export function generateSignatureReportPDF(
  records: ConsentLog[],
  options: ReportOptions
): Buffer {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });
  
  const pageWidth = doc.internal.pageSize.getWidth();
  let currentY = 55;
  const lineHeight = 7;
  const leftMargin = 10;
  const pageHeight = doc.internal.pageSize.getHeight();
  const bottomMargin = 30;
  
  // Add watermark and header to first page
  addWatermark(doc);
  addHeader(doc, options);
  
  // Table headers
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  
  const colWidths = {
    id: 15,
    userId: 30,
    action: 25,
    timestamp: 40,
    verified: 18,
    hash: 50,
  };
  
  let colX = leftMargin;
  
  doc.text("ID", colX, currentY);
  colX += colWidths.id;
  
  doc.text("User ID", colX, currentY);
  colX += colWidths.userId;
  
  doc.text("Action", colX, currentY);
  colX += colWidths.action;
  
  doc.text("Timestamp", colX, currentY);
  colX += colWidths.timestamp;
  
  doc.text("Verified", colX, currentY);
  colX += colWidths.verified;
  
  doc.text("Signature Hash", colX, currentY);
  
  currentY += lineHeight;
  
  // Draw line under headers
  doc.setLineWidth(0.3);
  doc.line(leftMargin, currentY, pageWidth - leftMargin, currentY);
  currentY += 2;
  
  // Table data
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  
  let pageNumber = 1;
  
  for (const record of records) {
    // Check if we need a new page
    if (currentY > pageHeight - bottomMargin) {
      // Add footer to current page
      addFooter(doc, pageNumber, Math.ceil(records.length / 20) + 1);
      
      // New page
      doc.addPage();
      pageNumber++;
      currentY = 20;
      
      // Add watermark to new page
      addWatermark(doc);
      
      // Repeat headers
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      colX = leftMargin;
      
      doc.text("ID", colX, currentY);
      colX += colWidths.id;
      doc.text("User ID", colX, currentY);
      colX += colWidths.userId;
      doc.text("Action", colX, currentY);
      colX += colWidths.action;
      doc.text("Timestamp", colX, currentY);
      colX += colWidths.timestamp;
      doc.text("Verified", colX, currentY);
      colX += colWidths.verified;
      doc.text("Signature Hash", colX, currentY);
      
      currentY += lineHeight;
      doc.setLineWidth(0.3);
      doc.line(leftMargin, currentY, pageWidth - leftMargin, currentY);
      currentY += 2;
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
    }
    
    // Print row data
    colX = leftMargin;
    
    doc.text(String(record.id), colX, currentY);
    colX += colWidths.id;
    
    doc.text(record.userId.substring(0, 25), colX, currentY);
    colX += colWidths.userId;
    
    doc.text(record.action, colX, currentY);
    colX += colWidths.action;
    
    doc.text(
      record.timestamp ? format(new Date(record.timestamp), 'yyyy-MM-dd HH:mm:ss') : 'N/A',
      colX,
      currentY
    );
    colX += colWidths.timestamp;
    
    doc.text(record.verified ? 'Yes' : 'No', colX, currentY);
    colX += colWidths.verified;
    
    doc.text(record.signatureHash.substring(0, 40) + '...', colX, currentY);
    
    currentY += lineHeight;
  }
  
  // Add footer to last page
  const totalPages = pageNumber;
  addFooter(doc, pageNumber, totalPages);
  
  // Summary footer
  currentY += 10;
  if (currentY > pageHeight - bottomMargin) {
    doc.addPage();
    addWatermark(doc);
    currentY = 20;
    pageNumber++;
    addFooter(doc, pageNumber, totalPages);
  }
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text(`Total Records: ${records.length}`, leftMargin, currentY);
  
  // Return PDF as buffer
  return Buffer.from(doc.output('arraybuffer'));
}

/**
 * Generate CSV export for signature consent logs
 */
export function generateSignatureReportCSV(records: ConsentLog[]): string {
  const headers = [
    'ID',
    'Signature ID',
    'User ID',
    'Action',
    'Timestamp',
    'Verified',
    'Signature Hash',
    'OTP ID',
    'Fayda ID',
    'Entity Type',
    'Entity ID',
  ];
  
  const rows = records.map(record => [
    record.id,
    record.signatureId,
    record.userId,
    record.action,
    record.timestamp ? format(new Date(record.timestamp), 'yyyy-MM-dd HH:mm:ss') : 'N/A',
    record.verified ? 'Yes' : 'No',
    record.signatureHash,
    record.otpId || 'N/A',
    record.faydaId || 'N/A',
    record.relatedEntityType || 'N/A',
    record.relatedEntityId || 'N/A',
  ]);
  
  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.map(cell => `"${cell}"`).join(',')),
  ].join('\n');
  
  return csvContent;
}

/**
 * Generate JSON export for signature consent logs
 */
export function generateSignatureReportJSON(records: ConsentLog[]): string {
  const exportData = {
    exportDate: new Date().toISOString(),
    totalRecords: records.length,
    records: records.map(record => ({
      id: record.id,
      signatureId: record.signatureId,
      userId: record.userId,
      action: record.action,
      timestamp: record.timestamp,
      verified: record.verified,
      signatureHash: record.signatureHash,
      otpId: record.otpId,
      faydaId: record.faydaId,
      relatedEntityType: record.relatedEntityType,
      relatedEntityId: record.relatedEntityId,
      metadata: record.metadata,
    })),
  };
  
  return JSON.stringify(exportData, null, 2);
}
